title: Faaiz Anwar
logo: /assets/img/Profile_image .jpg
#description: Operations Coordinator @ Coding With Kids | Recent Computer Science Graduate from Seattle University 
show_downloads: true
theme: jekyll-theme-minimal
